apiVersion: v1
kind: Service
metadata:
  name: app-frontend
  namespace: "monitoring-progress-michal"
  labels:
    app: app-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: app-frontend
